project:
  type: website
  output-dir: docs

website:
  site-url: "https://christinaf075.github.io"
  title: "Christina Fan"
  description: "Welcome to my academic website."
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: CV
        href: files/CV-Christina Fan 2025 (5).pdf


format:
  html:
    theme: lumen
    css: styles.css
    toc: true



