project:
  type: website
  output-dir: christinaf075.github.io

website:
  site-url: "https://christinaf075.github.io"
  title: "ChristinaFan"
  description: "Welcome to test Fan's academic website"
  navbar:
    left:
      - text: Home
        href: index.qmd


format:
  html:
    theme: lumen
    css: styles.css
    toc: true



