project:
  type: website
  output-dir: docs

website:
  site-url: "https://christinaf075.github.io"
  title: "ChristinaFan"
  description: "Welcome to test Fan's academic website"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd


format:
  html:
    theme:
      - lumen
      - brand
    css: styles.css
    toc: true



